### PRODUCTS

### Find all products
GET /api/products HTTP/1.1
Host: localhost:8080

### Find product by ID

GET /products/1 HTTP/1.1
Host: localhost:8080

### Add product

POST /products HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Nowy produkt",
  "imageUrl": "url-obrazka",
  "price": 9.99,
  "stock": 10
}

### Update product

PUT /products/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Zaktualizowany produkt",
  "imageUrl": "nowy-url-obrazka",
  "price": 14.99,
  "stock": 5
}


### Delete product
DELETE /products/1 HTTP/1.1
Host: localhost:8080

### CART ROWS

###  Find all Cart Rows

GET /cart-rows/1 HTTP/1.1
Host: localhost:8080

### Find by ID Cart Rows

GET /cartrows HTTP/1.1
Host: localhost:8080

### Create Cart

POST /cart-rows HTTP/1.1
Host: localhost:8080
Content-Type: application/json




### Update by ID Cart Rows

PUT /cartrows HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "productId": 1,
  "quantity": 1
}

### Delete Cart Row by ID

DELETE /cartrows/1 HTTP/1.1
Host: localhost:8080

###

# curl -X POST -H "Content-Type: application/json" -d '{"productId": 1, "quantity": 2}' http://localhost:8080/cart/1/items
POST http://localhost:8080/cart/1/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

###


